server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVER
          uri: lb://USER-SERVER
          predicates:
            - Path=/user/**

        - id: DEPARTMENT-SERVER
          uri: lb://DEPARTMENT-SERVER
          predicates:
            - Path=/department/**

